import type { Agent, AppNotification, Dataset, Evaluation, KBStats } from './types';

export const datasets: Dataset[] = [
  {
    id: 'truthfulqa',
    name: 'TruthfulQA',
    description: 'Questions designed to elicit common human misconceptions, used to measure truthfulness and hallucination propensity.',
    records: 817,
    status: 'Active',
    lastUpdated: '2026-08-22',
    chunks: 4821,
    embeddings: 4821,
  },
  {
    id: 'squad',
    name: 'SQuAD',
    description: 'Stanford Question Answering Dataset — reading comprehension passages with crowdsourced Q&A pairs for grounded retrieval.',
    records: 87599,
    status: 'Active',
    lastUpdated: '2026-08-20',
    chunks: 23441,
    embeddings: 23441,
  },
  {
    id: 'hotpotqa',
    name: 'HotpotQA',
    description: 'Multi-hop question answering requiring reasoning across multiple supporting documents.',
    records: 90447,
    status: 'Indexing',
    lastUpdated: '2026-08-25',
    chunks: 51200,
    embeddings: 41200,
  },
  {
    id: 'fever',
    name: 'FEVER',
    description: 'Fact Extraction and VERification — claims with verified supporting/refuting evidence for hallucination training.',
    records: 185445,
    status: 'Idle',
    lastUpdated: '2026-08-15',
    chunks: 64210,
    embeddings: 64210,
  },
];

export const kbStats: KBStats = {
  totalDocuments: 12507,
  totalChunks: 84368,
  totalEmbeddings: 83672,
  datasets: datasets.length,
  lastUpdated: '2026-08-25T10:42:00',
};

export const agents: Agent[] = [
  { id: 'relevance', name: 'Relevance Judge Agent', purpose: 'Evaluates whether the response directly answers the user\'s question.', status: 'Active', icon: 'Target', model: 'gpt-4o-mini', weight: 0.25 },
  { id: 'accuracy', name: 'Accuracy Judge Agent', purpose: 'Checks factual correctness using available reference information.', status: 'Active', icon: 'ShieldCheck', model: 'gpt-4o-mini', weight: 0.30 },
  { id: 'hallucination', name: 'Hallucination Detection Agent', purpose: 'Identifies unsupported or fabricated claims.', status: 'Active', icon: 'Search', model: 'gpt-4o', weight: 0.25 },
  { id: 'completeness', name: 'Completeness Judge Agent', purpose: 'Checks whether important information is missing.', status: 'Active', icon: 'ListChecks', model: 'gpt-4o-mini', weight: 0.15 },
  { id: 'verdict', name: 'Verdict Agent', purpose: 'Combines evaluation results and produces the final verdict.', status: 'Active', icon: 'Gavel', model: 'gpt-4o', weight: 0.05 },
];

export const evaluations: Evaluation[] = [
  {
    id: 'EVAL-2026-0418',
    question: 'What is the capital of Australia?',
    response: 'The capital of Australia is Sydney, which is the largest city in the country and the seat of the federal government.',
    referenceAnswer: 'The capital of Australia is Canberra, a planned city located in the Australian Capital Territory.',
    scores: { relevance: 9.0, accuracy: 4.2, hallucination: 3.0, completeness: 7.0, overall: 5.4 },
    verdict: 'Poor',
    hallucination: true,
    hallucinationRisk: 'High',
    claims: [
      { id: 'c1', text: 'The capital of Australia is Sydney.', status: 'Contradicted', evidence: 'Canberra is the capital per the Constitution and ACT charter.', confidence: 0.98, explanation: 'Directly contradicts verified reference. Sydney is the largest city, not the capital.' },
      { id: 'c2', text: 'Sydney is the largest city in the country.', status: 'Supported', evidence: 'ABS population data 2024.', confidence: 0.95, explanation: 'Consistent with census data.' },
      { id: 'c3', text: 'Sydney is the seat of the federal government.', status: 'Contradicted', evidence: 'Parliament House is in Canberra.', confidence: 0.97, explanation: 'Federal parliament sits in Canberra, not Sydney.' },
    ],
    evidence: [
      { id: 'e1', source: 'Wikipedia', dataset: 'SQuAD', text: 'Canberra is the capital city of Australia, located in the Australian Capital Territory...', similarity: 0.94, chunkId: '#124' },
      { id: 'e2', source: 'Encyclopaedia', dataset: 'FEVER', text: 'The seat of government for the Commonwealth of Australia is Canberra, not Sydney.', similarity: 0.89, chunkId: '#3092' },
    ],
    strengths: ['Directly addresses the question asked', 'Fluent and well-structured prose'],
    weaknesses: ['Contains a fabricated capital claim (Sydney instead of Canberra)', 'Incorrectly states federal government seat', 'High hallucination risk on core fact'],
    confidence: 0.96,
    summary: 'The response confidently states Sydney is the capital of Australia and seat of government. Both claims are contradicted by retrieved evidence. Hallucination risk is high.',
    recommendation: 'Response should be rejected and regenerated with grounding. Critical factual errors on the primary claim.',
    date: '2026-08-25T09:14:00',
    durationMs: 18230,
  },
  {
    id: 'EVAL-2026-0417',
    question: 'Explain the difference between supervised and unsupervised learning.',
    response: 'Supervised learning uses labeled data to train models to predict outputs, while unsupervised learning finds patterns in unlabeled data without predefined outputs. Common supervised algorithms include linear regression and decision trees; unsupervised examples include k-means clustering and PCA.',
    referenceAnswer: 'Supervised learning trains on labeled input-output pairs; unsupervised learning discovers structure in unlabeled data.',
    scores: { relevance: 9.2, accuracy: 8.8, hallucination: 9.0, completeness: 8.4, overall: 8.8 },
    verdict: 'Good',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Supervised learning uses labeled data.', status: 'Supported', evidence: 'Standard ML textbook definition.', confidence: 0.97, explanation: 'Consistent with canonical definitions.' },
      { id: 'c2', text: 'Unsupervised learning finds patterns in unlabeled data.', status: 'Supported', evidence: 'Standard ML textbook definition.', confidence: 0.96, explanation: 'Consistent with canonical definitions.' },
      { id: 'c3', text: 'k-means and PCA are unsupervised algorithms.', status: 'Supported', evidence: 'Algorithm taxonomy reference.', confidence: 0.93, explanation: 'Both are widely categorized as unsupervised.' },
    ],
    evidence: [
      { id: 'e1', source: 'ML Textbook', dataset: 'SQuAD', text: 'Supervised learning is the machine learning task of learning a function that maps input to output based on labeled pairs.', similarity: 0.91, chunkId: '#8821' },
    ],
    strengths: ['Directly answers the question', 'Factually supported by standard definitions', 'Includes concrete algorithm examples', 'No hallucination detected'],
    weaknesses: ['Could mention reinforcement learning for completeness', 'No discussion of semi-supervised learning'],
    confidence: 0.94,
    summary: 'A clear, factually grounded explanation comparing supervised and unsupervised learning. All claims are supported by retrieved reference material.',
    recommendation: 'Response can be accepted with minor additions for completeness.',
    date: '2026-08-24T15:02:00',
    durationMs: 14210,
  },
  {
    id: 'EVAL-2026-0416',
    question: 'Who wrote the theory of general relativity?',
    response: 'Albert Einstein developed the theory of general relativity, publishing it in 1915. It describes gravity as the curvature of spacetime caused by mass and energy.',
    referenceAnswer: 'Albert Einstein published general relativity in 1915.',
    scores: { relevance: 9.5, accuracy: 9.0, hallucination: 9.5, completeness: 9.0, overall: 9.2 },
    verdict: 'Excellent',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Einstein developed general relativity.', status: 'Supported', evidence: 'Historical record, Britannica.', confidence: 0.99, explanation: 'Well-documented historical fact.' },
      { id: 'c2', text: 'Published in 1915.', status: 'Supported', evidence: 'Annalen der Physik publication record.', confidence: 0.98, explanation: 'Matches publication history.' },
      { id: 'c3', text: 'Gravity is curvature of spacetime.', status: 'Supported', evidence: 'Core principle of GR.', explanation: 'Fundamental tenet of general relativity.', confidence: 0.96 },
    ],
    evidence: [
      { id: 'e1', source: 'Britannica', dataset: 'FEVER', text: 'Albert Einstein presented his theory of general relativity to the Prussian Academy in 1915.', similarity: 0.95, chunkId: '#1182' },
    ],
    strengths: ['Directly and completely answers the question', 'Factually accurate with correct date', 'Concise yet complete', 'No hallucination detected'],
    weaknesses: ['Could mention special relativity as precursor'],
    confidence: 0.97,
    summary: 'An accurate, concise, well-grounded response. All claims supported by retrieved evidence.',
    recommendation: 'Response can be accepted as-is.',
    date: '2026-08-23T11:28:00',
    durationMs: 11840,
  },
  {
    id: 'EVAL-2026-0415',
    question: 'What is the boiling point of water on Mount Everest?',
    response: 'Water boils at approximately 70°C on Mount Everest due to the reduced atmospheric pressure at high altitude.',
    referenceAnswer: 'At ~8,848 m altitude, water boils around 68-70°C.',
    scores: { relevance: 8.8, accuracy: 8.5, hallucination: 8.8, completeness: 7.5, overall: 8.4 },
    verdict: 'Good',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Water boils at ~70°C on Everest.', status: 'Supported', evidence: 'Atmospheric pressure tables.', confidence: 0.91, explanation: 'Matches known altitude-pressure-boiling data.' },
      { id: 'c2', text: 'Reduced atmospheric pressure lowers boiling point.', status: 'Supported', evidence: 'Physics reference.', confidence: 0.95, explanation: 'Correct physical principle.' },
    ],
    evidence: [
      { id: 'e1', source: 'Physics Handbook', dataset: 'SQuAD', text: 'At 8848 meters, atmospheric pressure is about 253 mmHg, giving a boiling point near 70°C.', similarity: 0.88, chunkId: '#4291' },
    ],
    strengths: ['Directly answers the question', 'Physically correct explanation', 'No hallucination'],
    weaknesses: ['Could specify the exact altitude', 'No mention of pressure value'],
    confidence: 0.90,
    summary: 'A correct, well-grounded response on altitude-dependent boiling point.',
    recommendation: 'Response can be accepted with minor improvements.',
    date: '2026-08-22T08:45:00',
    durationMs: 15120,
  },
  {
    id: 'EVAL-2026-0414',
    question: 'Describe the function of mitochondria.',
    response: 'Mitochondria are the powerhouse of the cell, generating ATP through cellular respiration. They were independently discovered by Isaac Newton in 1687.',
    referenceAnswer: 'Mitochondria produce ATP via oxidative phosphorylation.',
    scores: { relevance: 7.0, accuracy: 5.0, hallucination: 4.0, completeness: 6.5, overall: 5.6 },
    verdict: 'Needs Improvement',
    hallucination: true,
    hallucinationRisk: 'High',
    claims: [
      { id: 'c1', text: 'Mitochondria generate ATP.', status: 'Supported', evidence: 'Biology textbook.', confidence: 0.98, explanation: 'Correct core function.' },
      { id: 'c2', text: 'Discovered by Isaac Newton in 1687.', status: 'Contradicted', evidence: 'Mitochondria discovered by Albert von Kölliker (1857).', confidence: 0.99, explanation: 'Fabricated attribution; Newton worked on physics, not cell biology.' },
    ],
    evidence: [
      { id: 'e1', source: 'Biology Text', dataset: 'SQuAD', text: 'Mitochondria were first described by Albert von Kölliker in 1857.', similarity: 0.86, chunkId: '#7012' },
    ],
    strengths: ['Correctly identifies ATP production'],
    weaknesses: ['Fabricated historical claim about Newton', 'Hallucination on discovery attribution', 'Lacks detail on oxidative phosphorylation'],
    confidence: 0.95,
    summary: 'The response correctly describes ATP production but contains a fabricated claim that Isaac Newton discovered mitochondria. High hallucination risk.',
    recommendation: 'Response should be regenerated. The Newton attribution is a fabricated hallucination.',
    date: '2026-08-21T14:10:00',
    durationMs: 16780,
  },
  {
    id: 'EVAL-2026-0413',
    question: 'What causes the Northern Lights?',
    response: 'The Northern Lights, or aurora borealis, are caused by solar wind particles colliding with gases in Earth\'s atmosphere, exciting them to emit light.',
    referenceAnswer: 'Aurora borealis results from solar wind particles exciting atmospheric gases.',
    scores: { relevance: 9.0, accuracy: 8.7, hallucination: 9.0, completeness: 8.0, overall: 8.7 },
    verdict: 'Good',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Solar wind particles collide with atmospheric gases.', status: 'Supported', evidence: 'Atmospheric physics reference.', confidence: 0.96, explanation: 'Correct mechanism.' },
      { id: 'c2', text: 'Excited gases emit light.', status: 'Supported', evidence: 'Atomic emission physics.', confidence: 0.95, explanation: 'Correct physical principle.' },
    ],
    evidence: [
      { id: 'e1', source: 'NASA', dataset: 'FEVER', text: 'Auroras occur when charged particles from the solar wind excite atmospheric atoms.', similarity: 0.92, chunkId: '#5521' },
    ],
    strengths: ['Correct mechanism', 'Concise', 'No hallucination'],
    weaknesses: ['Could mention specific gases (oxygen, nitrogen)', 'No mention of color dependence'],
    confidence: 0.92,
    summary: 'A correct, well-grounded explanation of aurora borealis.',
    recommendation: 'Response can be accepted with minor additions.',
    date: '2026-08-20T10:30:00',
    durationMs: 12940,
  },
  {
    id: 'EVAL-2026-0412',
    question: 'How does photosynthesis work?',
    response: 'Photosynthesis converts light energy into chemical energy stored in glucose. It occurs in chloroplasts using chlorophyll, water, and CO₂, producing oxygen as a byproduct.',
    referenceAnswer: 'Photosynthesis converts light, water, and CO₂ into glucose and oxygen.',
    scores: { relevance: 9.5, accuracy: 9.0, hallucination: 9.5, completeness: 8.5, overall: 9.1 },
    verdict: 'Excellent',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Photosynthesis converts light to chemical energy.', status: 'Supported', evidence: 'Biology reference.', confidence: 0.98, explanation: 'Correct.' },
      { id: 'c2', text: 'Occurs in chloroplasts using chlorophyll.', status: 'Supported', evidence: 'Cell biology.', confidence: 0.97, explanation: 'Correct.' },
    ],
    evidence: [
      { id: 'e1', source: 'Biology Text', dataset: 'SQuAD', text: 'Photosynthesis occurs in the chloroplasts of plant cells using chlorophyll.', similarity: 0.93, chunkId: '#2201' },
    ],
    strengths: ['Complete and accurate', 'Mentions all key inputs/outputs', 'No hallucination'],
    weaknesses: ['Could mention light and dark reactions'],
    confidence: 0.96,
    summary: 'A complete, accurate explanation of photosynthesis.',
    recommendation: 'Response can be accepted as-is.',
    date: '2026-08-19T16:20:00',
    durationMs: 11320,
  },
  {
    id: 'EVAL-2026-0411',
    question: 'What is the speed of light?',
    response: 'The speed of light in a vacuum is approximately 299,792 kilometers per second.',
    referenceAnswer: 'Approximately 299,792,458 m/s in vacuum.',
    scores: { relevance: 9.0, accuracy: 7.5, hallucination: 8.5, completeness: 7.0, overall: 8.0 },
    verdict: 'Acceptable',
    hallucination: false,
    hallucinationRisk: 'Low',
    claims: [
      { id: 'c1', text: 'Speed of light is ~299,792 km/s.', status: 'Supported', evidence: 'Physics constant.', confidence: 0.93, explanation: 'Numerically correct but stated in km/s where m/s is conventional; value is right.' },
    ],
    evidence: [
      { id: 'e1', source: 'Physics Reference', dataset: 'FEVER', text: 'The speed of light in vacuum is exactly 299,792,458 m/s.', similarity: 0.90, chunkId: '#3001' },
    ],
    strengths: ['Numerically accurate', 'Directly answers'],
    weaknesses: ['Uses km/s unit (less common)', 'No mention of medium dependence'],
    confidence: 0.88,
    summary: 'Accurate value but unconventional units. Generally acceptable.',
    recommendation: 'Response can be accepted; consider unit clarification.',
    date: '2026-08-18T09:00:00',
    durationMs: 10420,
  },
];

export const notifications: AppNotification[] = [
  { id: 'n1', title: 'Evaluation completed', body: 'EVAL-2026-0418 finished with verdict: Poor (hallucination detected).', time: '2 min ago', type: 'error', read: false },
  { id: 'n2', title: 'Knowledge base updated', body: 'HotpotQA indexing reached 80% (41,200 / 51,200 embeddings).', time: '1 hour ago', type: 'info', read: false },
  { id: 'n3', title: 'Report generated', body: 'Evaluation report for EVAL-2026-0417 is ready to download.', time: '3 hours ago', type: 'success', read: false },
  { id: 'n4', title: 'Dataset imported', body: 'FEVER dataset re-indexed successfully.', time: '1 day ago', type: 'success', read: true },
  { id: 'n5', title: 'Evaluation failed', body: 'EVAL-2026-0410 timed out during retrieval. Retrying automatically.', time: '2 days ago', type: 'warning', read: true },
];

// Timeseries for analytics (last 30 days, sampled to 14 points)
export const performanceTrend = [
  { date: 'Aug 12', overall: 7.8, accuracy: 7.5, relevance: 8.1, hallucination: 8.4, completeness: 7.6 },
  { date: 'Aug 13', overall: 8.0, accuracy: 7.8, relevance: 8.3, hallucination: 8.6, completeness: 7.7 },
  { date: 'Aug 14', overall: 7.9, accuracy: 7.6, relevance: 8.2, hallucination: 8.5, completeness: 7.8 },
  { date: 'Aug 15', overall: 8.2, accuracy: 8.0, relevance: 8.4, hallucination: 8.7, completeness: 8.0 },
  { date: 'Aug 16', overall: 8.1, accuracy: 7.9, relevance: 8.5, hallucination: 8.6, completeness: 7.9 },
  { date: 'Aug 17', overall: 8.4, accuracy: 8.2, relevance: 8.6, hallucination: 8.8, completeness: 8.1 },
  { date: 'Aug 18', overall: 8.3, accuracy: 8.1, relevance: 8.5, hallucination: 8.7, completeness: 8.0 },
  { date: 'Aug 19', overall: 8.6, accuracy: 8.4, relevance: 8.7, hallucination: 8.9, completeness: 8.3 },
  { date: 'Aug 20', overall: 8.5, accuracy: 8.3, relevance: 8.6, hallucination: 8.8, completeness: 8.2 },
  { date: 'Aug 21', overall: 7.2, accuracy: 6.5, relevance: 8.0, hallucination: 7.0, completeness: 7.4 },
  { date: 'Aug 22', overall: 8.1, accuracy: 7.9, relevance: 8.4, hallucination: 8.5, completeness: 7.8 },
  { date: 'Aug 23', overall: 8.8, accuracy: 8.6, relevance: 8.9, hallucination: 9.0, completeness: 8.5 },
  { date: 'Aug 24', overall: 8.7, accuracy: 8.5, relevance: 8.8, hallucination: 8.9, completeness: 8.4 },
  { date: 'Aug 25', overall: 8.0, accuracy: 7.2, relevance: 8.5, hallucination: 8.0, completeness: 7.6 },
];

export const verdictDistribution: { verdict: string; count: number; color: string }[] = [
  { verdict: 'Excellent', count: 142, color: '#12b767' },
  { verdict: 'Good', count: 286, color: '#3385ff' },
  { verdict: 'Acceptable', count: 98, color: '#06cf87' },
  { verdict: 'Needs Improvement', count: 54, color: '#f79009' },
  { verdict: 'Poor', count: 31, color: '#f04438' },
];

export const hallucinationStats = {
  total: 611,
  detected: 87,
  free: 524,
  highRisk: 23,
};

export const KB_SEARCH_RESULTS = [
  { id: 'r1', text: 'Canberra is the capital city of Australia, located in the Australian Capital Territory.', source: 'Wikipedia', dataset: 'SQuAD', similarity: 0.94, docType: 'Encyclopedia', chunkId: '#124' },
  { id: 'r2', text: 'The seat of government for the Commonwealth of Australia is Canberra, not Sydney.', source: 'Britannica', dataset: 'FEVER', similarity: 0.89, docType: 'Reference', chunkId: '#3092' },
  { id: 'r3', text: 'Canberra was selected as the capital in 1908 as a compromise between Sydney and Melbourne.', source: 'History Archive', dataset: 'HotpotQA', similarity: 0.82, docType: 'Article', chunkId: '#1820' },
  { id: 'r4', text: 'Parliament House in Canberra opened in 1988 and is the meeting place of the Parliament of Australia.', source: 'Gov.au', dataset: 'SQuAD', similarity: 0.78, docType: 'Official', chunkId: '#5512' },
];
